### ISSUE TITLE
README should be updated for current presentation and file structure

### ISSUE THREAD

**Issue by MicFin** [ga-wdi-boston/rails-api-single-resource#21]
1.  Command should not include `--skip-template-engine` and should be called with `bin/rails` 

> Rails has a number of generator tools for creating boilerplate files very quickly. To spin up a new controller, we can just run `rails g controller books --skip-template-engine`

Should be

> Rails has a number of generator tools for creating boilerplate files very quickly. To spin up a new controller, we can just run `bin/rails g controller books`

2.  Use `resource` and `except` since we use the generator 

> Add the following code to config/routes.rb:
> 
> get '/books', to: 'books#index'

Should be
> Add the following code to config/routes.rb:
> 
> `resources :books, :except => [:new, :edit] #verify which routes should be excluded`

@jrhorn424 will add a comment after lesson to expand on necessary updates.

**Comment by raq929** [comment]
We should also use the longhand form `rails generate` instead of `rails g`
