### ISSUE TITLE
There are  demo-CA-lab sections for update and patch, but no post

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/rails-api-single-resource#25]
One of either update or patch should be post.

**Comment by MicFin** [comment]
These 3 should be '#create' not '#patch'.

Change

> Demo: BooksController#patch
> Code-along: PatientsController#patch
> Lab: IngredientsController#patch

To

> Demo: BooksController#create
> Code-along: PatientsController#create
> Lab: IngredientsController#create
